#See https://confluence.infobip.com/display/IT/Remoting+Library+Documentation properties section
#JVM properties can be specified in docker/etc/app/jvm.conf

spring.profiles.active: development

server.port: HTTP_SERVER_PORT

hazelcast.cluster.addresses: ${HAZELCAST_CLUSTER_ADDRESSES:localhost}

infobip.remoting:
  server:
    autostart: false
    properties:
      mml.rmi.enabled: false
spring:
  datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://FR-OTHER-2.ancotel.local:1433/GenApiDB;useNTLMv2=true;domain=ancotel.local
    username: DATABASE_USER
    password: DATABASE_PASSWORD
  flyway:
    baseline-on-migrate: true
    schemas: dbo
    enabled: false
