spring.profiles.active: development

server.port: 8080

hazelcast.cluster.addresses: ${HAZELCAST_CLUSTER_ADDRESSES:localhost}


spring:
  datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: DATABASE_USER
    username: DATABASE_USER
    password: DATABASE_PASSWORD