#
# The properties defined here will be applied on top of those from application.yml if the active profile is "development".
#
# Practical usage:
# - setting various URLs to those in the integration environment
#

infobip.remoting:
  server:
    autostart: true # automatically start RMI server (this should be set to false in production; Deployment Manager will start your server)
    properties:
      http:
        rmi:
          enabled: true
          remoting.endpoint: "http://localhost:${server.port}/rmi"
          root.remoting.path: /,/rmi


spring:
  datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://FR-OTHER-2.ancotel.local:1433/GenApiDB;useNTLMv2=true;domain=ancotel.local
    username: DATABASE_USER
    password: DATABASE_PASSWORD
  flyway:
    baseline-on-migrate: true
    schemas: dbo
    enabled: false
